#!/bin/bash

# List files in current directory
echo "Current Directory:"
ls -l

# Move to the parent directory
cd ..

# List files in the parent directory
echo "Parent Directory:"
ls -l

# Move to the /boot directory
cd /boot

# List files in the /boot directory
echo "/boot Directory:"
ls -l

